### ISSUE TITLE
Cinnamon 4.8 crashes on login due to flatpak

### ISSUE THREAD

**Issue by ronyala** [linuxmint/mint20.1-beta#41]
Cinnamon 4.8 crashes on login due to a flatpak issue, reference https://github.com/linuxmint/cinnamon/issues/9738.
Reposting here as this is a regression in cinnamon 4.8 caused by the changes to flatpak integration.
I am willing to help if possible.

**Comment by mtwebster** [comment]
What version of cinnamon-menus? This was thought to have been fixed by https://github.com/linuxmint/cinnamon-menus/commit/d63a35f42add18ecca7e587406b46014d91abc80 (part of cinnamon-menus 4.8.1).

**Comment by ronyala** [comment]
Hi, I updated cinnamon and cinnamon-menus, and I can confirm this still happens using cinnamon-menus 4.8.2 and cinnamon 4.8.3 (latest from daily builds)

**Comment by mtwebster** [comment]
Is there a specific flatpak app this is failing on?

edit: Also, did you restart cinnamon after the update? (sorry have to be sure)

**Comment by ronyala** [comment]
I've now uninstalled all flatpak apps (`flatpak list` doesn't show any apps now) and the crash still happens.
Yes, I did restart cinnamon.
I also made sure now that uninstalling `flatpak` itself does prevent the crash

**Comment by mtwebster** [comment]
Can you look in:
`/var/lib/flatpak/exports/share/applications`
and 
`~/.local/share/flatpak/exports/share/applications`

They should be empty if you have no flatpaks installed. There could be something leftover in there causing an issue. If there are any files, save them for troubleshooting please.

Thanks

**Comment by ronyala** [comment]
`/var/lib/flatpak/exports/share/applications` had only 1 file called `mimeinfo.cache`, and moving it outside the folder did not help.
`~/.local/share/flatpak/exports/share/applications` doesn't exist in my case (`~/.local/share/flatpak` doens't have an `exports` folder)

**Comment by mtwebster** [comment]
This may be fixed now - I can't reproduce it so I'm not 100% certain but it at least addresses a potential problem anyhow.

I'll try to get it built on the daily PPA soon.

I'm still not sure how this hinges on whether or not flatpak is installed.  The one thing it *does* do is add more paths to the XDG_DATA_DIRS environment variable.  In each of those a share folder may be, and in the share folders, an applications folder may exist. This tells me there's a flatpak .desktop file in one of those additional folders that's missing an `X-Flatpak` entry.

Maybe check your environment (`env | grep XDG_DATA_DIRS`) and see if there's some rogue .desktop file for a flatpak app.

**Comment by mtwebster** [comment]
The daily ppa is up-to-date now with the cinnamon build if anyone wants to try. Thanks

**Comment by ronyala** [comment]
Hi, it works! Thanks

I tried looking through .desktop files that are in XDG_DATA_DIRS paths, but there are just too many of them. I can try to print some data on the file when it happens to track it down, if it can lead to a 'better' fix?

**Comment by clefebvre** [comment]
This commit shipped as part of the cinnamon 4.8.4 update. Let me know if this fixes it and if we can close this issue.

**Comment by mtwebster** [comment]
@ronyala - we fixed the cause of the crash. It'd be nice to see the app file that exposed the problem just for completeness, but it's not a big deal.
